# Generated by Django 3.1 on 2020-09-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_email', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=200)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('available', models.BooleanField(max_length=200)),
            ],
        ),
    ]
